version: '3.9'

volumes:
  nexus2-data:

services:
  nexus:
    image: sonatype/nexus
    volumes:
      - nexus2-data:/sonatype-work
    ports:
      - "8081:8081"
  snyk-broker:
    image: snyk/broker:nexus2
    ports:
      - "7341:7341"
    environment:
      - BROKER_TOKEN=<token>
      - BASE_NEXUS_URL=http://test:test@nexus:8081
      - NEXUS_URL=http://test:test@nexus:8081/nexus/content
      - RES_BODY_URL_SUB=http://nexus:8081/nexus/content/repositories
      - BROKER_HEALTHCHECK_PATH=/healthcheck
      - BROKER_CLIENT_VALIDATION_URL=http://test:test@nexus:8081/nexus/service/local/status
      - LOG_LEVEL=trace
